version: 0.2

# Buildspec to generate test data before running E2E in parallel. It is important that all test data is independent of each other.

batch:
  fast-fail: true


phases:
  install:
    runtime-versions:
      java: corretto17
  pre_build:
    commands:
      - export ROLE_ARM=arn:aws:iam::282305091481:role/service-role/codebuild-warmup-service-role
      - aws sts assume-role --role-arn $ROLE_ARN --role-session-name test > Credentials
  build:
    commands:
      - gradle clean build
      - gradle gatlingRun-no.sikt.nva.speedtest.SpeedTest